# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 04:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('centre', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geom', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('extent', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('o365_group', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Channel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
