# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='channel',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
