# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20160526_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
