# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='modified_date',
            new_name='modified',
        ),
    ]
