sudo: false
language: python
cache: pip
dist: xenial
python:
    - 3.7
services:
    - postgresql
    - docker
addons:
    postgresql: 9.6
    apt:
        packages:
            - postgresql-9.6-postgis-2.3
branches:
    only:
        - master
env:
    global:
        - SECRET_KEY="SecretKeyForTravisCI"
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
before_install:
    - docker build -t dbcawa/oim-cms .
install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
before_script:
    - psql -U postgres -c "create database travis_ci_test;"
    - psql -U postgres -d travis_ci_test -c "create extension postgis;"
    - python manage.py migrate --noinput
script:
    - python manage.py test
