# Generated by Django 2.0.3 on 2018-04-18 06:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('rich_text', wagtail.core.blocks.RichTextBlock()), ('raw', wagtail.core.blocks.RawHTMLBlock()), ('include_content', wagtail.core.blocks.CharBlock()), ('content_list', wagtail.core.blocks.CharBlock())), blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Content updated date')),
                ('template_filename', models.CharField(choices=[('content.html', 'content.html'), ('f6-content.html', 'f6-content.html'), ('f6-vue.html', 'f6-vue.html')], default='f6-content.html', max_length=64)),
            ],
            options={
                'ordering': ('date',),
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='core.Content')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_contenttag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.ContentTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
