# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160115_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='template_filename',
            field=models.CharField(choices=[('content.html', 'content.html'), ('f6-content.html', 'f6-content.html'), ('f6-vue.html', 'f6-vue.html')], default='content.html', max_length=64),
        ),
    ]
