# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 02:39
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtailmarkdown


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160115_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock()), ('raw', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('include_content', wagtail.wagtailcore.blocks.CharBlock()), ('content_list', wagtail.wagtailcore.blocks.CharBlock()), ('markdown', wagtailmarkdown.MarkdownBlock())], blank=True, null=True),
        ),
    ]
