# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='extension',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
