# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20161019_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='username',
            field=models.CharField(editable=False, help_text='Pre-Windows 2000 login username.', max_length=128, unique=True),
        ),
    ]
