# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-03 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20161024_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='active',
            field=models.BooleanField(default=True, editable=False, help_text='Account is active within Active Directory.'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_deleted',
            field=models.BooleanField(default=False, editable=False, help_text='Account has been deleted in Active Directory.'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='cost_centres_secondary',
            field=models.ManyToManyField(blank=True, help_text='NOTE: this provides security group access (e.g. T drives).', related_name='cost_centres_secondary', to='organisation.CostCentre'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='date_ad_updated',
            field=models.DateTimeField(editable=False, help_text='The date when the AD account was last updated.', null=True, verbose_name='Date AD updated'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='expiry_date',
            field=models.DateTimeField(editable=False, help_text='Date that the AD account is set to expire.', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='extension',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='VoIP extension'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='in_sync',
            field=models.BooleanField(default=False, editable=False, help_text='CMS data has been synchronised from AD data.'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='org_units_secondary',
            field=models.ManyToManyField(blank=True, help_text='NOTE: this provides email distribution group access.', related_name='org_units_secondary', to='organisation.OrgUnit'),
        ),
    ]
