# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_auto_20161104_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='cost_centres_secondary',
            field=models.ManyToManyField(blank=True, editable=False, help_text='NOTE: this provides security group access (e.g. T drives).', related_name='cost_centres_secondary', to='organisation.CostCentre'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='org_units_secondary',
            field=models.ManyToManyField(blank=True, editable=False, help_text='NOTE: this provides email distribution group access.', related_name='org_units_secondary', to='organisation.OrgUnit'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='secondary_locations',
            field=models.ManyToManyField(blank=True, help_text='Only to be used for staff working in additional loactions from their cost centre', to='organisation.Location'),
        ),
    ]
