# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import organisation.models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_auto_20170407_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='HR Employee ID', max_length=128, null=True, unique=True, validators=[organisation.models.validate_employee_id], verbose_name='Employee ID'),
        ),
    ]
