# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_auto_20170518_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_guid',
            field=models.CharField(help_text='Locally stored GUID. This field must match GUID in the AD object for sync to be successful', max_length=48, null=True, unique=True),
        ),
    ]
