# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_auto_20170619_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
