# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_orgunit_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
