# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_auto_20170702_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_guid',
            field=models.CharField(blank=True, help_text='Locally stored GUID. This field must match GUID in the AD object for sync to be successful', max_length=48, null=True, unique=True),
        ),
    ]
