# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0018_costcentre_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='unit_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Department'), (1, 'Division'), (11, 'Sub-Division'), (2, 'Branch'), (3, 'Region'), (4, 'Cost Centre'), (5, 'Office'), (6, 'District'), (7, 'Section'), (8, 'Unit'), (9, 'Group'), (10, 'Work centre')], default=4),
        ),
    ]
