# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0019_auto_20170703_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentre',
            name='chart_acct_name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='chart of accounts name'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='name',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='unit_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Department'), (1, 'Division (Tier two)'), (11, 'Division (Tier three)'), (9, 'Group'), (2, 'Branch'), (7, 'Section'), (3, 'Region'), (6, 'District'), (8, 'Unit'), (5, 'Office'), (10, 'Work centre')]),
        ),
    ]
