# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0021_auto_20170704_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_dn',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True, unique=True),
        ),
    ]
