# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0025_auto_20170706_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='Date that the AD account is set to expire.', null=True),
        ),
    ]
