# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0027_auto_20170706_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'L1 User Account - Permanent'), (3, 'L1 User Account - Agency contract'), (0, 'L1 User Account - Department fixed-term contract'), (8, 'L1 User Account - Seasonal'), (6, 'L1 User Account - Vendor'), (7, 'L1 User Account - Volunteer'), (1, 'L1 User Account - Other/Alumni'), (11, 'L1 User Account - RoomMailbox'), (12, 'L1 User Account - EquipmentMailbox'), (10, 'L2 Service Account - System'), (5, 'L1 Group (shared) Mailbox - Shared account'), (9, 'L1 Role Account - Role-based account'), (4, 'Terminated'), (14, 'Unknown - AD disabled'), (15, 'Cleanup - Permanent'), (16, 'Unknown - AD active')], help_text='Employee account status (should match Alesco status)', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='HR Employee ID.', max_length=128, null=True, unique=True, verbose_name='Employee ID'),
        ),
    ]
