# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0028_auto_20170707_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='notes',
            field=models.TextField(blank=True, help_text='Records relevant to any AD account extension, expiry or deletion (e.g. ticket #).', null=True),
        ),
    ]
