# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0029_auto_20170707_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='azure_guid',
            field=models.CharField(blank=True, help_text='Azure AD GUID.', max_length=48, null=True, unique=True),
        ),
    ]
