# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0032_auto_20170717_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='username',
            field=models.CharField(blank=True, editable=False, help_text='Pre-Windows 2000 login username.', max_length=128, null=True),
        ),
    ]
