# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 04:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0025_auto_20160901_1548'),
        ('registers', '0042_auto_20160902_1209'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('support', models.TextField(blank=True, help_text='Support timeframe or scope')),
                ('support_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('oss', models.NullBooleanField(default=None, help_text='Open-source/free software license?')),
                ('used_licenses', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('available_licenses', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('license_details', models.TextField(blank=True, help_text='Direct license keys or details')),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit')),
                ('primary_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.DepartmentUser')),
            ],
            options={
                'db_table': 'assets_softwarelicense',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('details', models.TextField(blank=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
            ],
            options={
                'db_table': 'assets_vendor',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.Vendor'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
