# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-19 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20161019_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAssetExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_no', models.CharField(blank=True, help_text='The Telephone number of the Device', max_length=40, null=True)),
                ('fax_no', models.CharField(blank=True, help_text='The Fax number of the Device', max_length=40, null=True)),
                ('icc_id', models.CharField(blank=True, help_text='The ICC ID number', max_length=40, null=True)),
                ('msisdn', models.CharField(blank=True, max_length=24, null=True)),
                ('service_provider', models.CharField(blank=True, help_text='Name of Provider', max_length=100, null=True)),
                ('service_plan', models.CharField(blank=True, help_text='Name of Provider Plan', max_length=100, null=True)),
                ('sim_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_pin', models.CharField(blank=True, max_length=10, null=True)),
                ('date_modified', models.DateField(default=datetime.datetime.now)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('comms_type', models.CharField(max_length=100)),
                ('vtd_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address1', models.CharField(max_length=255, null=True)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('address3', models.CharField(max_length=255, null=True)),
                ('suburb', models.CharField(max_length=255, null=True)),
                ('postcode', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(choices=[('N/A', 'N/A'), ('ACT', 'ACT'), ('NSW', 'NSW'), ('NT', 'NT'), ('QLD', 'QLD'), ('VIC', 'VIC'), ('TAS', 'TAS'), ('SA', 'SA'), ('WA', 'WA')], default='N/A', max_length=5, null=True)),
                ('effective_from', models.DateField(null=True)),
                ('effective_to', models.DateField(null=True)),
                ('date_modified', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('rego', models.CharField(blank=True, help_text='Vehicle Registration', max_length=20, null=True)),
                ('make', models.CharField(blank=True, help_text='Vehicle Make', max_length=120, null=True)),
                ('model', models.CharField(blank=True, help_text='Vehicle Model', max_length=120, null=True)),
                ('kms', models.IntegerField(blank=True, null=True)),
                ('light_flag', models.NullBooleanField(default=None)),
                ('category', models.CharField(blank=True, help_text='Category', max_length=170, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('default_job_id', models.CharField(blank=True, help_text='JOB ID', max_length=40, null=True)),
                ('month_cost', models.IntegerField(blank=True, null=True)),
                ('status_flag', models.CharField(blank=True, max_length=2, null=True)),
                ('cost_centre', models.CharField(blank=True, max_length=20, null=True)),
                ('manufactured_month_year', models.DateField(blank=True, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=40, null=True)),
                ('diesel_engine', models.NullBooleanField(default=None)),
                ('automatic_engine', models.NullBooleanField(default=None)),
                ('tare', models.IntegerField(blank=True, null=True)),
                ('gcm', models.IntegerField(blank=True, null=True)),
                ('serial_chassis_no', models.CharField(blank=True, max_length=60, null=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=120, null=True)),
                ('comments2', models.CharField(blank=True, max_length=120, null=True)),
                ('comments3', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='rsid',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='hardwareasset',
            name='status',
            field=models.CharField(choices=[('In storage', 'In storage'), ('Deployed', 'Deployed'), ('Disposed', 'Disposed'), ('Available', 'Available'), ('Decommissioned', 'Decommissioned'), ('Hired', 'Hired'), ('In Service', 'In Service'), ('Lost', 'Lost'), ('Return to Manufacturer', 'Return to Manufacturer'), ('Sold', 'Sold'), ('Stolen', 'Stolen'), ('Location unknown', 'Location unknown'), ('Invalid', 'Invalid')], default='In storage', max_length=50),
        ),
        migrations.AlterField(
            model_name='hardwaremodel',
            name='model_type',
            field=models.CharField(choices=[('Air conditioner', 'Air conditioner'), ('Camera - Compact', 'Camera - Compact'), ('Camera - SLR', 'Camera - SLR'), ('Camera - Security (IP)', 'Camera - Security (IP)'), ('Camera - Security (non-IP)', 'Camera - Security (non-IP)'), ('Camera - Other', 'Camera - Other'), ('Chassis', 'Chassis'), ('Computer - Desktop', 'Computer - Desktop'), ('Computer - Docking station', 'Computer - Docking station'), ('Computer - Input device', 'Computer - Input device'), ('Computer - Laptop', 'Computer - Laptop'), ('Computer - Misc Accessory', 'Computer - Misc Accessory'), ('Computer - Monitor', 'Computer - Monitor'), ('Computer - Tablet PC', 'Computer - Tablet PC'), ('Computer - Other', 'Computer - Other'), ('Comms - Airband Handheld', 'Comms - Airband Handheld'), ('Comms - SIM - BGAN', 'Comms - SIM - BGAN'), ('Comms - Radio Over IP', 'Comms - Radio Over IP'), ('Comms - UHF', 'Comms - UHF'), ('Comms - VHF', 'Comms - VHF'), ('Comms - HF', 'Comms - HF'), ('Comms - Dual Band VH/U', 'Comms - Dual Band VH/U'), ('Comms - Satellite Phone', 'Comms - Satellite Phone'), ('Comms - SIM - Satellite Phone', 'Comms - SIM - Satellite Phone'), ('Comms - BGAN', 'Comms - BGAN'), ('Comms - rBGAN', 'Comms - rBGAN'), ('Comms - 2 Way Satellite System', 'Comms - 2 Way Satellite System'), ('Comms - Satellite System (DEC VSAT)', 'Comms - Satellite System (DEC VSAT)'), ('Comms - Automatic Weather Station', 'Comms - Automatic Weather Station'), ('Comms - Satellite Base Telephone', 'Comms - Satellite Base Telephone'), ('Comms - Telephone Interface', 'Comms - Telephone Interface'), ('Comms - FMS Cache', 'Comms - FMS Cache'), ('Comms - Communications Bus', 'Comms - Communications Bus'), ('Comms - Mobile Communication Vehicle', 'Comms - Mobile Communication Vehicle'), ('Comms - Tracking Device', 'Comms - Tracking Device'), ('Comms - Explorer PTT Terminal', 'Comms - Explorer PTT Terminal'), ('Comms - Codan Portable Repeater', 'Comms - Codan Portable Repeater'), ('Comms - VHF (Digital)', 'Comms - VHF (Digital)'), ('Environmental monitor', 'Environmental monitor'), ('Network - Hub', 'Network - Hub'), ('Network - Media converter', 'Network - Media converter'), ('Network - Modem', 'Network - Modem'), ('Network - Module or card', 'Network - Module or card'), ('Network - Power injector', 'Network - Power injector'), ('Network - Router', 'Network - Router'), ('Network - Switch (Ethernet)', 'Network - Switch (Ethernet)'), ('Network - Switch (FC)', 'Network - Switch (FC)'), ('Network - Wireless AP', 'Network - Wireless AP'), ('Network - Wireless bridge', 'Network - Wireless bridge'), ('Network - Wireless controller', 'Network - Wireless controller'), ('Network - Other', 'Network - Other'), ('Phone - Conference', 'Phone - Conference'), ('Phone - Desk', 'Phone - Desk'), ('Phone - Gateway', 'Phone - Gateway'), ('Phone - Mobile', 'Phone - Mobile'), ('Phone - Wireless or portable', 'Phone - Wireless or portable'), ('Phone - Other', 'Phone - Other'), ('Power Distribution Unit', 'Power Distribution Unit'), ('Printer - Fax machine', 'Printer - Fax machine'), ('Printer - Local', 'Printer - Local'), ('Printer - Local Multifunction', 'Printer - Local Multifunction'), ('Printer - Multifunction copier', 'Printer - Multifunction copier'), ('Printer - Plotter', 'Printer - Plotter'), ('Printer - Workgroup', 'Printer - Workgroup'), ('Printer - Other', 'Printer - Other'), ('Projector', 'Projector'), ('Rack', 'Rack'), ('Server - Blade', 'Server - Blade'), ('Server - Rackmount', 'Server - Rackmount'), ('Server - Tower', 'Server - Tower'), ('Storage - Disk array', 'Storage - Disk array'), ('Storage - NAS', 'Storage - NAS'), ('Storage - SAN', 'Storage - SAN'), ('Storage - Other', 'Storage - Other'), ('Speaker', 'Speaker'), ('Tablet', 'Tablet'), ('Tape autoloader', 'Tape autoloader'), ('Tape drive', 'Tape drive'), ('UPS', 'UPS'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='hardwareassetextra',
            name='ha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.HardwareAsset'),
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.Suppliers'),
        ),
    ]
