# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_computer_location'),
        ('assets', '0002_auto_20161019_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwarelicense',
            old_name='primary_user',
            new_name='assigned_user',
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='tracked_computer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.Computer'),
        ),
    ]
