# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-28 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20161222_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('rego', models.CharField(blank=True, help_text='Vehicle Registration', max_length=20, null=True)),
                ('make', models.CharField(blank=True, help_text='Vehicle Make', max_length=120, null=True)),
                ('model', models.CharField(blank=True, help_text='Vehicle Model', max_length=120, null=True)),
                ('kms', models.IntegerField(blank=True, null=True)),
                ('light_flag', models.NullBooleanField(default=None)),
                ('category', models.CharField(blank=True, help_text='Category', max_length=170, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('default_job_id', models.CharField(blank=True, help_text='JOB ID', max_length=40, null=True)),
                ('month_cost', models.IntegerField(blank=True, null=True)),
                ('status_flag', models.CharField(blank=True, max_length=2, null=True)),
                ('cost_centre', models.CharField(blank=True, max_length=20, null=True)),
                ('manufactured_month_year', models.DateField(blank=True, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=40, null=True)),
                ('diesel_engine', models.NullBooleanField(default=None)),
                ('automatic_engine', models.NullBooleanField(default=None)),
                ('tare', models.IntegerField(blank=True, null=True)),
                ('gcm', models.IntegerField(blank=True, null=True)),
                ('serial_chassis_no', models.CharField(blank=True, max_length=60, null=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=120, null=True)),
                ('comments2', models.CharField(blank=True, max_length=120, null=True)),
                ('comments3', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
