# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-28 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_vehicledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareassetextra',
            name='vtd_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
