# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-30 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20161230_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareassetextra',
            name='vehicle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
