# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20171012_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaremodel',
            name='model_type',
            field=models.CharField(choices=[('Air conditioner', 'Air conditioner'), ('Camera - Compact', 'Camera - Compact'), ('Camera - Conference', 'Camera - Conference'), ('Camera - SLR', 'Camera - SLR'), ('Camera - Security (IP)', 'Camera - Security (IP)'), ('Camera - Security (non-IP)', 'Camera - Security (non-IP)'), ('Camera - Other', 'Camera - Other'), ('Chassis', 'Chassis'), ('Computer - Desktop', 'Computer - Desktop'), ('Computer - Docking station', 'Computer - Docking station'), ('Computer - Input device', 'Computer - Input device'), ('Computer - Laptop', 'Computer - Laptop'), ('Computer - Misc Accessory', 'Computer - Misc Accessory'), ('Computer - Monitor', 'Computer - Monitor'), ('Computer - Peripheral', 'Computer - Peripheral'), ('Computer - Tablet PC', 'Computer - Tablet PC'), ('Computer - Other', 'Computer - Other'), ('Environmental monitor', 'Environmental monitor'), ('Network - Hub', 'Network - Hub'), ('Network - Media converter', 'Network - Media converter'), ('Network - Modem', 'Network - Modem'), ('Network - Module or card', 'Network - Module or card'), ('Network - Music On Hold', 'Network - Music On Hold'), ('Network - Power injector', 'Network - Power injector'), ('Network - Router', 'Network - Router'), ('Network - Switch (Ethernet)', 'Network - Switch (Ethernet)'), ('Network - Switch (FC)', 'Network - Switch (FC)'), ('Network - Wireless AP', 'Network - Wireless AP'), ('Network - Wireless bridge', 'Network - Wireless bridge'), ('Network - Wireless controller', 'Network - Wireless controller'), ('Network - Other', 'Network - Other'), ('Office Equipment - Other', 'Office Equipment - Other'), ('Phone - Conference', 'Phone - Conference'), ('Phone - Desk', 'Phone - Desk'), ('Phone - Gateway', 'Phone - Gateway'), ('Phone - Mobile', 'Phone - Mobile'), ('Phone - Wireless or portable', 'Phone - Wireless or portable'), ('Phone - Other', 'Phone - Other'), ('Power Distribution Unit', 'Power Distribution Unit'), ('Printer - Fax machine', 'Printer - Fax machine'), ('Printer - Local', 'Printer - Local'), ('Printer - Local Multifunction', 'Printer - Local Multifunction'), ('Printer - Multifunction copier', 'Printer - Multifunction copier'), ('Printer - Plotter', 'Printer - Plotter'), ('Printer - Server', 'Printer - Server'), ('Printer - Workgroup', 'Printer - Workgroup'), ('Printer - Other', 'Printer - Other'), ('Projector', 'Projector'), ('Rack', 'Rack'), ('Server - Blade', 'Server - Blade'), ('Server - Rackmount', 'Server - Rackmount'), ('Server - Tower', 'Server - Tower'), ('Storage - Disk array', 'Storage - Disk array'), ('Storage - Hard Drive', 'Storage - Hard Drive'), ('Storage - NAS', 'Storage - NAS'), ('Storage - SAN', 'Storage - SAN'), ('Storage - Other', 'Storage - Other'), ('Speaker', 'Speaker'), ('Tablet', 'Tablet'), ('Tape autoloader', 'Tape autoloader'), ('Tape drive', 'Tape drive'), ('Telecom - Testing Device', 'Telecom - Testing Device'), ('UPS', 'UPS'), ('Other', 'Other')], help_text='The broad category of this hardware model.', max_length=50),
        ),
    ]
