# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180131_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareasset',
            name='invoice_copy',
            field=models.FileField(blank=True, help_text='A digital copy of the asset invoice (e.g. PDF, JPG or PNG)', max_length=512, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='warranty_end',
            field=models.DateField(blank=True, help_text='Expiry date of hardware warranty period (if applicable).', null=True),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='invoice_copy',
            field=models.FileField(blank=True, help_text='A digital copy of the asset invoice (e.g. PDF, JPG or PNG)', max_length=512, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
