# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20180301_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(help_text='A digital copy of the asset invoice (e.g. PDF, JPG or PNG)', max_length=512, upload_to='uploads/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='org_unit',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='hardwareasset',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='hardwareasset',
            name='invoice_copy',
        ),
        migrations.RemoveField(
            model_name='softwareasset',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='softwareasset',
            name='invoice_copy',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='hardwareinvoice',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.HardwareAsset'),
        ),
    ]
