# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20180308_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwaremodel',
            name='lifecycle',
        ),
    ]
