# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 02:06
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20160310_1053'),
        ('registers', '0013_auto_20160303_1444')
    ]

    operations = [
        migrations.RunSQL([
            ("GRANT SELECT ON tracking_departmentuser TO {};".format(settings.POSTGREST_ROLE), None),
            ("GRANT SELECT ON registers_orgunit TO {};".format(settings.POSTGREST_ROLE), None)
        ])
    ]
