# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('hours_of_service', models.CharField(blank=True, max_length=50)),
                ('contact_instructions', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state_or_province', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PycswConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=b'en-US', max_length=10)),
                ('max_records', models.IntegerField(default=10)),
                ('transactions', models.BooleanField(default=False, help_text=b'Enable transactions')),
                ('allowed_ips', models.CharField(blank=True, default=b'127.0.0.1', help_text=b'IP addresses that are allowed to make transaction requests', max_length=255)),
                ('harvest_page_size', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('keywords_type', models.CharField(max_length=255)),
                ('fees', models.CharField(max_length=100)),
                ('access_constraints', models.CharField(max_length=255)),
                ('repository_filter', models.CharField(blank=True, max_length=255)),
                ('inspire_enabled', models.BooleanField(default=False)),
                ('inspire_languages', models.CharField(blank=True, max_length=255)),
                ('inspire_default_language', models.CharField(blank=True, max_length=30)),
                ('inspire_date', models.DateTimeField(blank=True, null=True)),
                ('gemet_keywords', models.CharField(blank=True, max_length=255)),
                ('conformity_service', models.CharField(blank=True, max_length=255)),
                ('temporal_extent_start', models.DateTimeField(blank=True, null=True)),
                ('temporal_extent_end', models.DateTimeField(blank=True, null=True)),
                ('point_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Collaborator')),
            ],
            options={
                'verbose_name': 'PyCSW Configuration',
                'verbose_name_plural': 'PyCSW Configuration',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, help_text=b'Maps to pycsw:Identifier', max_length=255)),
                ('title', models.CharField(help_text=b'Maps to pycsw:Title', max_length=255, null=True)),
                ('typename', models.CharField(db_index=True, default=b'gmd:MD_Metadata', help_text=b'Maps to pycsw:Typename', max_length=100)),
                ('schema', models.CharField(db_index=True, default=b'http://www.isotc211.org/2005/gmd', help_text=b'Maps to pycsw:Schema', max_length=100)),
                ('insert_date', models.DateTimeField(auto_now_add=True, help_text=b'Maps to pycsw:InsertDate')),
                ('xml', models.TextField(default=b'<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd"/>', help_text=b' Maps to pycsw:XML')),
                ('any_text', models.TextField(help_text=b'Maps to pycsw:AnyText')),
                ('modified', models.DateTimeField(blank=True, help_text=b'Maps to pycsw:Modified', null=True)),
                ('bounding_box', models.TextField(blank=True, help_text=b'Maps to pycsw:BoundingBox', null=True)),
                ('abstract', models.TextField(blank=True, help_text=b'Maps to pycsw:Abstract', null=True)),
                ('keywords', models.CharField(blank=True, help_text=b'Maps to pycsw:Keywords', max_length=255, null=True)),
                ('kmi_slug', models.CharField(blank=True, help_text=b'Maps to pycsw:KMISlug', max_length=255, null=True)),
                ('lineage', models.TextField(blank=True, help_text=b'Maps to pycsw:Lineage', null=True)),
                ('positional_acc', models.TextField(blank=True, help_text=b'Maps to pycsw:PositionalAccuracy', null=True)),
                ('attribute_acc', models.TextField(blank=True, help_text=b'Maps to pycsw:AttributeAccuracy', null=True)),
                ('completeness', models.TextField(blank=True, help_text=b'Maps to pycsw:Complete', null=True)),
                ('manual_override', models.BooleanField(default=False)),
                ('sld', models.TextField(blank=True, help_text=b'Maps to pycsw:SLD', null=True)),
                ('qml', models.TextField(blank=True, help_text=b'Maps to pycsw:QML', null=True)),
                ('lyr', models.TextField(blank=True, help_text=b'Maps to pycsw:LAYER', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('format', models.CharField(choices=[(b'SLD', b'SLD'), (b'QML', b'QML'), (b'LYR', b'LYR')], max_length=3)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='styles',
            field=models.ManyToManyField(to='catalogue.Style'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='catalogue.Organization'),
        ),
    ]
