# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='lyr',
            field=models.CharField(blank=True, help_text=b'Maps to pycsw:LAYER', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='qml',
            field=models.CharField(blank=True, help_text=b'Maps to pycsw:QML', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='sld',
            field=models.CharField(blank=True, help_text=b'Maps to pycsw:SLD', max_length=255, null=True),
        ),
    ]
