# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20160304_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='styles',
        ),
        migrations.AddField(
            model_name='style',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='catalogue.Record'),
        ),
    ]
