# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20160304_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
