# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20160304_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='attribute_acc',
        ),
        migrations.RemoveField(
            model_name='record',
            name='completeness',
        ),
        migrations.RemoveField(
            model_name='record',
            name='kmi_slug',
        ),
        migrations.RemoveField(
            model_name='record',
            name='lineage',
        ),
        migrations.RemoveField(
            model_name='record',
            name='positional_acc',
        ),
        migrations.AddField(
            model_name='record',
            name='is_raster',
            field=models.BooleanField(default=False, help_text=b'Raster layer if set to true and Vector layer if set to false'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='links',
            field=models.TextField(blank=True, help_text=b'Maps to pycsw:Links', null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='publication_date',
            field=models.DateTimeField(blank=True, help_text=b'Maps to pycsw:PublicationDate', null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='service_type',
            field=models.CharField(blank=True, help_text=b'Maps to pycsw:ServiceType', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='service_type_version',
            field=models.CharField(blank=True, help_text=b'Maps to pycsw:ServiceTypeVersion', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='lyr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='qml',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='sld',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='format',
            field=models.CharField(choices=[(b'SLD', b'SLD'), (b'QML', b'QML'), (b'LYR', b'LAYER')], max_length=3),
        ),
    ]
