# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20160315_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='is_raster',
        ),
        migrations.RemoveField(
            model_name='record',
            name='manual_override',
        ),
        migrations.AddField(
            model_name='record',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='record',
            name='auto_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='record',
            name='crs',
            field=models.CharField(blank=True, help_text=b'Maps to pycsw:CRS', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='bounding_box',
            field=models.TextField(blank=True, help_text=b"Maps to pycsw:BoundingBox.It's a WKT geometry", null=True),
        ),
    ]
