# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_style_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='content',
            field=models.FileField(blank=True, default=b'', upload_to=b'/mnt/storage/Apps/oim-cms/media/catalogue/styles'),
        ),
    ]
