# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20160316_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='checksum',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
