# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_style_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='any_text',
            field=models.TextField(help_text=b'Maps to pycsw:AnyText', null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='checksum',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='style',
            name='content',
            field=models.FileField(blank=True, default=b'', upload_to=b'/home/rocky/work/repository/oim-cms/media/catalogue/styles'),
        ),
    ]
