# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20160321_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='schema',
            field=models.CharField(db_index=True, default=b'', help_text=b'Maps to pycsw:Schema', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='typename',
            field=models.CharField(db_index=True, default=b'', help_text=b'Maps to pycsw:Typename', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='xml',
            field=models.TextField(default=b'', help_text=b' Maps to pycsw:XML'),
        ),
    ]
