# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20160322_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='lyr',
        ),
        migrations.RemoveField(
            model_name='record',
            name='qml',
        ),
        migrations.RemoveField(
            model_name='record',
            name='sld',
        ),
        migrations.AddField(
            model_name='pycswconfig',
            name='service_type_version',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='any_text',
            field=models.TextField(blank=True, help_text=b'Maps to pycsw:AnyText', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='schema',
            field=models.CharField(blank=True, db_index=True, default=b'', editable=False, help_text=b'Maps to pycsw:Schema', max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='typename',
            field=models.CharField(blank=True, db_index=True, default=b'', editable=False, help_text=b'Maps to pycsw:Typename', max_length=100),
        ),
        migrations.AlterField(
            model_name='style',
            name='content',
            field=models.FileField(blank=True, default=b'', upload_to=b'/mnt/storage/Apps/oim-cms/media/catalogue/styles'),
        ),
    ]
