# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20160322_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pycswconfig',
            name='service_type_version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
