# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_data_20160329_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='links',
            field=models.TextField(blank=True, editable=False, help_text=b'Maps to pycsw:Links', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='service_type_version',
            field=models.CharField(blank=True, editable=False, help_text=b'Maps to pycsw:ServiceTypeVersion', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(blank=True, help_text=b'Maps to pycsw:Title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='xml',
            field=models.TextField(default=b'', editable=False, help_text=b' Maps to pycsw:XML'),
        ),
        migrations.AlterField(
            model_name='style',
            name='content',
            field=models.FileField(upload_to=b'catalogue/styles'),
        ),
        migrations.AlterField(
            model_name='style',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='catalogue.Record'),
        ),
    ]
