# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 04:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20160329_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-z0-9_]+$'), b'Slug can only contain lowercase letters, numbers and underscores', b'invalid')])),
                ('description', models.TextField(blank=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Application')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Record')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='applicationlayer',
            unique_together=set([('application', 'layer')]),
        ),
    ]
