# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 05:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20160330_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='applicationlayer',
            options={'ordering': ['application', 'order', 'layer']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['identifier']},
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[a-z0-9_]+$'), b'Slug can only contain lowercase letters, numbers and underscores', b'invalid')]),
        ),
    ]
