# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20160330_1354'),
    ]


    operations = [
        migrations.RunSQL("CREATE OR REPLACE VIEW catalogue_record_all AS SELECT * FROM catalogue_record WHERE active"),
    ]
