# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_recordview_20160401_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='records',
            field=models.ManyToManyField(to='catalogue.Record'),
        ),
        migrations.AddField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(to='catalogue.Tag'),
        ),
    ]
