# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20160701_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.Tag'),
        ),
    ]
