# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_auto_20160701_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='auto_update',
        ),
    ]
