# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20160711_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='legend',
            field=models.FileField(blank=True, null=True, upload_to=b'catalogue/legends'),
        ),
    ]
