# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_record_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='source_legend',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=b'catalogue/legends/source'),
        ),
    ]
