# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 04:42
from __future__ import unicode_literals

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_record_source_legend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='checksum',
        ),
        migrations.AlterField(
            model_name='style',
            name='content',
            field=models.FileField(storage=catalogue.models.StyleStorage(), upload_to=catalogue.models.styleFilePath),
        ),
    ]
