# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 03:49
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MudMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('last_saved', models.DateField()),
                ('geojson', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MudMapLineString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(null=True)),
                ('label', models.CharField(max_length=256, null=True)),
                ('colour', models.CharField(max_length=256, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('mudmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudmap.MudMap')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MudMapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(null=True)),
                ('label', models.CharField(max_length=256, null=True)),
                ('colour', models.CharField(max_length=256, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('mudmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudmap.MudMap')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MudMapPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(null=True)),
                ('label', models.CharField(max_length=256, null=True)),
                ('colour', models.CharField(max_length=256, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('mudmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mudmap.MudMap')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
