# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mudmap',
            name='last_saved',
            field=models.DateTimeField(),
        ),
    ]
