# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
        migrations.AddField(
            model_name='backup',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit'),
        ),
        migrations.AddField(
            model_name='device',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
        migrations.AddField(
            model_name='device',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit'),
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit'),
        ),
    ]
