# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        ('tracking', '0001_initial'),
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='computer',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.Computer'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.CostCentre'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Physical location', null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.Location'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='mobile',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.Mobile'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.OrgUnit'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.Software', verbose_name='operating system'),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='department_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organisation.DepartmentUser'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='functions',
            field=models.ManyToManyField(to='registers.BusinessFunction'),
        ),
        migrations.AddField(
            model_name='businessfunction',
            name='services',
            field=models.ManyToManyField(to='registers.BusinessService'),
        ),
        migrations.AddField(
            model_name='backup',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.CostCentre'),
        ),
        migrations.AddField(
            model_name='backup',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.OrgUnit'),
        ),
        migrations.AddField(
            model_name='backup',
            name='parent_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='host', to='registers.Hardware'),
        ),
        migrations.AddField(
            model_name='backup',
            name='system',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registers.Hardware'),
        ),
        migrations.AlterUniqueTogether(
            name='processitsystemrelationship',
            unique_together=set([('process', 'itsystem')]),
        ),
        migrations.AlterUniqueTogether(
            name='itsystemhardware',
            unique_together=set([('host', 'role')]),
        ),
        migrations.AlterUniqueTogether(
            name='itsystemdependency',
            unique_together=set([('itsystem', 'dependency')]),
        ),
        migrations.AlterUniqueTogether(
            name='hardware',
            unique_together=set([('computer', 'mobile')]),
        ),
    ]
