# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_auto_20151217_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarelicense',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
