# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_auto_20161003_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='backup_info',
            field=models.TextField(blank=True, help_text="Information about the backup/archiving of this system's data.", null=True, verbose_name='backup information'),
        ),
    ]
