# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_auto_20151217_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('fax', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='orgunit',
            name='svg',
        ),
        migrations.AddField(
            model_name='orgunit',
            name='secondary_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.SecondaryLocation'),
        ),
    ]
