# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20160101_1657'),
        ('registers', '0005_auto_20151217_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.DepartmentUser'),
        ),
        migrations.AddField(
            model_name='secondarylocation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.DepartmentUser'),
        ),
    ]
