# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20161019_1434'),
        ('registers', '0006_itsystem_other_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSystemVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='A description of the support and service arrangements provided by this vendor for the IT System. This should include details of the procedure for obtaining support.', null=True)),
            ],
            options={
                'ordering': ('itsystem__name', 'vendor__name'),
                'verbose_name': 'IT System vendor',
            },
        ),
        migrations.AddField(
            model_name='itsystem',
            name='sla',
            field=models.TextField(blank=True, help_text='Details of any Service Level Agreement that exists for this IT System (typically with an external vendor).', null=True, verbose_name='Service Level Agreement'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='system_id',
            field=models.CharField(max_length=16, unique=True, verbose_name='system ID'),
        ),
        migrations.AddField(
            model_name='itsystemvendor',
            name='itsystem',
            field=models.ForeignKey(help_text='The IT System', on_delete=django.db.models.deletion.PROTECT, to='registers.ITSystem', verbose_name='IT System'),
        ),
        migrations.AddField(
            model_name='itsystemvendor',
            name='vendor',
            field=models.ForeignKey(help_text='The vendor of the IT System', on_delete=django.db.models.deletion.PROTECT, to='assets.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='itsystemvendor',
            unique_together=set([('itsystem', 'vendor')]),
        ),
    ]
