# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 07:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0008_auto_20160112_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='mtd',
            field=models.DurationField(default=datetime.timedelta(14), help_text='Maximum Tolerable Downtime'),
        ),
        migrations.AddField(
            model_name='process',
            name='rpo',
            field=models.DurationField(default=datetime.timedelta(1), help_text='Recovery Point Objective/Data Loss Interval'),
        ),
        migrations.AddField(
            model_name='process',
            name='rto',
            field=models.DurationField(default=datetime.timedelta(7), help_text='Recovery Time Objective'),
        ),
        migrations.AddField(
            model_name='process',
            name='users',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
