# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-12 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0009_auto_20161212_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itsystemhardware',
            options={'verbose_name_plural': 'IT System hardware'},
        ),
        migrations.AlterUniqueTogether(
            name='itsystemhardware',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='itsystemhardware',
            name='host',
        ),
    ]
