# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0010_auto_20160114_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bandwidth_url',
            field=models.CharField(blank=True, help_text='URL to prtg graph of bw utilisation', max_length=2000, null=True),
        ),
    ]
