# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-13 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0011_auto_20161212_1535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hardware',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='org_unit',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='os',
        ),
        migrations.DeleteModel(
            name='Hardware',
        ),
    ]
