# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0011_location_bandwidth_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='service',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Service 1'), (2, 'Service 2'), (3, 'Service 3'), (4, 'Service 4'), (5, 'Service 5'), (6, 'Service 6'), (7, 'Service 7'), (8, 'Service 8'), (9, 'Common Service 9 - OIM'), (10, 'Common Service 10 - ODG'), (11, 'Common Service 11 - ???')], default=4),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='unit_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Department'), (1, 'Division'), (2, 'Branch'), (3, 'Region'), (4, 'Cost Centre'), (5, 'Office'), (6, 'District'), (7, 'Section')], default=4),
        ),
    ]
