# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0012_auto_20160127_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ('name', '-device_type'), 'verbose_name_plural': 'hardware'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'processes'},
        ),
    ]
