# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-13 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0012_auto_20161213_0931'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itsystemvendor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='itsystemvendor',
            name='itsystem',
        ),
        migrations.RemoveField(
            model_name='itsystemvendor',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='ITSystemVendor',
        ),
    ]
