# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-13 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0013_auto_20161213_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Software',
        ),
    ]
