# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0014_delete_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='biller_code',
            field=models.CharField(blank=True, help_text='BPAY biller code for this IT System (must be unique).', max_length=64, null=True),
        ),
    ]
