# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0014_auto_20160314_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itsystemhardware',
            options={'verbose_name_plural': 'IT system hardware'},
        ),
        migrations.AlterField(
            model_name='softwarelicense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.Vendor'),
        ),
    ]
