# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0015_itsystem_biller_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='oim_internal_only',
            field=models.BooleanField(default=False, help_text='For OIM use only'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='system_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'System - Web application'), (2, 'System - Client application'), (3, 'System - Mobile application'), (4, 'Service'), (5, 'System - Externally hosted application'), (6, 'Platform'), (7, 'Infrastructure')], null=True),
        ),
    ]
