# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0015_auto_20160314_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('functions', models.ManyToManyField(to='registers.BusinessFunction')),
            ],
            options={
                'verbose_name_plural': 'business processes',
            },
        ),
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Service number', unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessITSystemRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criticality', models.PositiveIntegerField(choices=[(1, 'Critical'), (2, 'Moderate'), (3, 'Low')])),
            ],
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='criticality',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Critical'), (2, 'Moderate'), (3, 'Low')], null=True),
        ),
        migrations.AddField(
            model_name='processitsystemrelationship',
            name='itsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.ITSystem'),
        ),
        migrations.AddField(
            model_name='processitsystemrelationship',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.BusinessProcess'),
        ),
        migrations.AddField(
            model_name='businessfunction',
            name='services',
            field=models.ManyToManyField(to='registers.BusinessService'),
        ),
        migrations.AlterUniqueTogether(
            name='processitsystemrelationship',
            unique_together=set([('process', 'itsystem')]),
        ),
    ]
