# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0016_auto_20170515_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itsystem',
            name='system_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'System - Web application'), (2, 'System - Client application'), (3, 'System - Mobile application'), (5, 'System - Externally hosted application'), (4, 'Service'), (6, 'Platform'), (7, 'Infrastructure')], null=True),
        ),
    ]
