# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0017_auto_20170518_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('db', 'Database'), ('dns', 'DNS'), ('email', 'Email'), ('idam', 'Identity & access management'), ('middle', 'Middleware'), ('phone', 'Phone system'), ('proxy', 'Reverse proxy'), ('storage', 'Storage'), ('vpn', 'VPN'), ('vm', 'Virtualisation'), ('web', 'Web server')], db_index=True, max_length=64)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together=set([('category', 'name')]),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='registers.Platform'),
        ),
    ]
