# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_auto_20160314_1337'),
        ('registers', '0018_auto_20160318_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='ah_support',
            field=models.ForeignKey(blank=True, help_text='After-hours support contact', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ah_support', to='tracking.DepartmentUser'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='bh_support',
            field=models.ForeignKey(blank=True, help_text='Business hours support contact', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bh_support', to='tracking.DepartmentUser'),
        ),
    ]
