# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0018_auto_20170530_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSystemEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(1, 'Incident'), (2, 'Maintenance'), (3, 'Information')])),
                ('description', models.TextField()),
                ('planned', models.BooleanField(default=False, help_text='Was this event planned?')),
                ('start', models.DateTimeField(help_text='Event start (date & time)')),
                ('duration', models.DurationField(blank=True, help_text='Optional: duration of the event (hh:mm:ss).', null=True)),
                ('end', models.DateTimeField(blank=True, help_text='Optional: event end (date & time)', null=True)),
                ('current', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'IT System event',
            },
        ),
    ]
