# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0019_auto_20160318_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='function',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='function',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='process',
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='mtd',
            field=models.DurationField(default=datetime.timedelta(14), help_text='Maximum Tolerable Downtime (days hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='rpo',
            field=models.DurationField(default=datetime.timedelta(1), help_text='Recovery Point Objective/Data Loss Interval (days hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='rto',
            field=models.DurationField(default=datetime.timedelta(7), help_text='Recovery Time Objective (days hh:mm:ss)'),
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
