# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0021_itsystemdependency_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystemhardware',
            name='production',
            field=models.BooleanField(default=False, help_text='Hardware is used by production IT system.'),
        ),
    ]
