# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0021_auto_20160318_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='recovery_docs',
            field=models.URLField(blank=True, help_text='URL to recovery procedure(s) in the event of system failure', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='system_reqs',
            field=models.TextField(blank=True, help_text='A written description of the requirements to use the system (e.g. web browser version)'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='system_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Web application'), (2, 'Client application'), (3, 'Mobile application'), (4, 'Service')], null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='technical_documentation',
            field=models.URLField(blank=True, help_text='URL to technical documentation', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='vulnerability_docs',
            field=models.URLField(blank=True, help_text='URL to documentation related to known vulnerability reports', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='workaround',
            field=models.TextField(blank=True, help_text='Written procedure for users to work around an outage of this system'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.Software', verbose_name='operating system'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='ah_support',
            field=models.ForeignKey(blank=True, help_text='After-hours support contact', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ah_support', to='tracking.DepartmentUser', verbose_name='after hours support'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='bh_support',
            field=models.ForeignKey(blank=True, help_text='Business hours support contact', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bh_support', to='tracking.DepartmentUser', verbose_name='business hours support'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='documentation',
            field=models.URLField(blank=True, help_text='URL to end-user documentation', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='link',
            field=models.CharField(blank=True, help_text='URL to web application', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='schema_url',
            field=models.URLField(blank=True, help_text='URL to schema diagram', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='status_html',
            field=models.URLField(blank=True, help_text='URL to status/uptime info', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='itsystemdependency',
            name='criticality',
            field=models.PositiveIntegerField(choices=[(1, 'Critical'), (2, 'Moderate'), (3, 'Low')], help_text='How critical is the dependency?'),
        ),
        migrations.AlterField(
            model_name='processitsystemrelationship',
            name='importance',
            field=models.PositiveIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], help_text='How important is the IT System to undertaking this process?'),
        ),
        migrations.AlterField(
            model_name='softwarelicense',
            name='available_licenses',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
