# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 03:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0022_auto_20160321_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprocess',
            name='mtd',
        ),
        migrations.RemoveField(
            model_name='businessprocess',
            name='rpo',
        ),
        migrations.RemoveField(
            model_name='businessprocess',
            name='rto',
        ),
        migrations.AddField(
            model_name='businessprocess',
            name='criticality',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Critical'), (2, 'Moderate'), (3, 'Low')], help_text='How critical is the process?', null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='mtd',
            field=models.DurationField(default=datetime.timedelta(14), help_text='Maximum Tolerable Downtime (days hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='rpo',
            field=models.DurationField(default=datetime.timedelta(1), help_text='Recovery Point Objective/Data Loss Interval (days hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='rto',
            field=models.DurationField(default=datetime.timedelta(7), help_text='Recovery Time Objective (days hh:mm:ss)'),
        ),
    ]
