# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0022_itsystemhardware_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystemhardware',
            name='decommissioned',
            field=models.BooleanField(default=False, help_text='Hardware has been decommissioned?'),
        ),
        migrations.AddField(
            model_name='itsystemhardware',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='custodian',
            field=models.ForeignKey(help_text='Application custodian', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systems_custodianed', to='organisation.DepartmentUser'),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='data_custodian',
            field=models.ForeignKey(blank=True, help_text='Application data custodian', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='systems_data_custodianed', to='organisation.DepartmentUser'),
        ),
    ]
