# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0023_auto_20160323_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='pobox',
            field=models.TextField(blank=True, verbose_name='PO Box'),
        ),
    ]
