# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 04:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0023_auto_20171012_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystemhardware',
            name='aws_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='AWS tags (key value pairs).', null=True),
        ),
    ]
