# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0024_auto_20160323_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itsystem',
            options={'ordering': ['name'], 'verbose_name': 'IT System'},
        ),
    ]
