# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0025_auto_20171017_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsystemhardware',
            name='aws_tags',
        ),
        migrations.AddField(
            model_name='itsystemhardware',
            name='patch_group',
            field=models.CharField(blank=True, help_text='Patch group that this host has been placed in.', max_length=256, null=True),
        ),
    ]
