# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0025_auto_20160509_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itsystemdependency',
            options={'verbose_name': 'IT System dependency', 'verbose_name_plural': 'IT System dependencies'},
        ),
        migrations.AddField(
            model_name='itsystem',
            name='contingency_plan',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='contingency_plan_status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Draft'), (2, 'Released'), (3, 'Superseded')], null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='device_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Network'), (2, 'Mobile'), (3, 'Domain PC'), (4, 'Hostname')]),
        ),
        migrations.AlterField(
            model_name='itsystemdependency',
            name='dependency',
            field=models.ForeignKey(help_text='The system which is depended upon by the IT System', on_delete=django.db.models.deletion.PROTECT, related_name='dependency', to='registers.ITSystem'),
        ),
    ]
