# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0026_auto_20171025_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystemhardware',
            name='host',
            field=models.CharField(blank=True, help_text='Host, or hosting environment.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='itsystemhardware',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Application server'), (2, 'Database server'), (3, 'Network file storage'), (4, 'Reverse proxy'), (5, 'Shared workstation')]),
        ),
    ]
