# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_auto_20160509_1313'),
        ('registers', '0026_auto_20160509_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_role', models.CharField(blank=True, help_text='The role in which the user is approving the document.', max_length=256, null=True)),
                ('evidence', models.FileField(blank=True, help_text='Optional evidence to support the document approval (email, etc.)', max_length=255, null=True, upload_to='uploads/%Y/%m/%d')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.DepartmentUser')),
            ],
        ),
        migrations.AddField(
            model_name='itsystem',
            name='contingency_plan_approvals',
            field=models.ManyToManyField(blank=True, to='registers.DocumentApproval'),
        ),
    ]
