# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0027_auto_20160510_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='contingency_plan_last_tested',
            field=models.DateField(blank=True, help_text='Date that the plan was last tested.', null=True),
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='contingency_plan',
            field=models.FileField(blank=True, help_text='NOTE: changes to this field will delete current contingency plan approvals.', max_length=255, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
