# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 06:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_auto_20160608_1400'),
        ('registers', '0028_auto_20160512_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshdeskConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Ticket attachments. An array of objects.', null=True)),
                ('body', models.TextField(blank=True, help_text='HTML content of the conversation.', null=True)),
                ('body_text', models.TextField(blank=True, help_text='Content of the conversation in plain text.', null=True)),
                ('cc_emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Email address added in the "cc" field of the conversation. An array of strings.', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('conversation_id', models.IntegerField(help_text='Unique ID of the conversation in Freshdesk.', unique=True)),
                ('incoming', models.BooleanField(default=False, help_text='Set to true if a particular conversation should appear as being created from outside.')),
                ('private', models.BooleanField(default=False, help_text='Set to true if the note is private.')),
                ('source', models.IntegerField(blank=True, help_text='Denotes the type of the conversation.', null=True)),
                ('ticket_id', models.IntegerField(help_text='ID of the ticket to which this conversation is being added.')),
                ('to_emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Email addresses of agents/users who need to be notified about this conversation. An array of strings.', null=True)),
                ('updated_at', models.DateTimeField(blank=True, help_text='Ticket updated timestamp.', null=True)),
                ('user_id', models.IntegerField(help_text='ID of the agent/user who is adding the conversation.')),
                ('du_user', models.ForeignKey(blank=True, help_text='Department User who is adding to the conversation.', null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.DepartmentUser')),
            ],
        ),
        migrations.CreateModel(
            name='FreshdeskTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Ticket attachments. An array of objects.', null=True)),
                ('cc_emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Email address added in the "cc" field of the incoming ticket email. An array of strings.', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('custom_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Key value pairs containing the names and values of custom fields.', null=True)),
                ('deleted', models.BooleanField(default=False, help_text='Set to true if the ticket has been deleted/trashed.')),
                ('description', models.TextField(blank=True, help_text='HTML content of the ticket.', null=True)),
                ('description_text', models.TextField(blank=True, help_text='Content of the ticket in plain text.', null=True)),
                ('due_by', models.DateTimeField(blank=True, help_text='Timestamp that denotes when the ticket is due to be resolved.', null=True)),
                ('email', models.CharField(blank=True, help_text='Email address of the requester.', max_length=256, null=True)),
                ('fr_due_by', models.DateTimeField(blank=True, help_text='Timestamp that denotes when the first response is due.', null=True)),
                ('fr_escalated', models.BooleanField(default=False, help_text='Set to true if the ticket has been escalated as the result of first response time being breached.')),
                ('fwd_emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Email address(e)s added while forwarding a ticket. An array of strings.', null=True)),
                ('group_id', models.IntegerField(blank=True, help_text='ID of the group to which the ticket has been assigned.', null=True)),
                ('is_escalated', models.BooleanField(default=False, help_text='Set to true if the ticket has been escalated for any reason.')),
                ('name', models.CharField(blank=True, help_text='Name of the requester.', max_length=256, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the requester.', max_length=256, null=True)),
                ('priority', models.IntegerField(blank=True, help_text='Priority of the ticket.', null=True)),
                ('reply_cc_emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Email address added while replying to a ticket. An array of strings.', null=True)),
                ('requester_id', models.IntegerField(blank=True, help_text='User ID of the requester.', null=True)),
                ('responder_id', models.IntegerField(blank=True, help_text='ID of the agent to whom the ticket has been assigned.', null=True)),
                ('source', models.IntegerField(blank=True, help_text='The channel through which the ticket was created.', null=True)),
                ('spam', models.BooleanField(default=False, help_text='Set to true if the ticket has been marked as spam.')),
                ('status', models.IntegerField(blank=True, help_text='Status of the ticket.', null=True)),
                ('subject', models.TextField(blank=True, help_text='Subject of the ticket.', null=True)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Tags that have been associated with the ticket. An array of strings.', null=True)),
                ('ticket_id', models.IntegerField(help_text='Unique ID of the ticket in Freshdesk.', unique=True)),
                ('to_emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Email addresses to which the ticket was originally sent. An array of strings.', null=True)),
                ('type', models.CharField(blank=True, help_text='Ticket type.', max_length=256, null=True)),
                ('updated_at', models.DateTimeField(blank=True, help_text='Ticket updated timestamp.', null=True)),
                ('du_requester', models.ForeignKey(blank=True, help_text='Department User who raised the ticket.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='du_requester', to='tracking.DepartmentUser')),
                ('du_responder', models.ForeignKey(blank=True, help_text='Department User to whom the ticket is assigned.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='du_responder', to='tracking.DepartmentUser')),
                ('it_system', models.ForeignKey(blank=True, help_text='IT System to which this ticket relates.', null=True, on_delete=django.db.models.deletion.CASCADE, to='registers.ITSystem')),
            ],
        ),
        migrations.AddField(
            model_name='freshdeskconversation',
            name='freshdesk_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registers.FreshdeskTicket'),
        ),
    ]
