# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0029_auto_20160608_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshdeskconversation',
            name='conversation_id',
            field=models.BigIntegerField(help_text='Unique ID of the conversation in Freshdesk.', unique=True),
        ),
        migrations.AlterField(
            model_name='freshdeskconversation',
            name='user_id',
            field=models.BigIntegerField(help_text='ID of the agent/user who is adding the conversation.'),
        ),
        migrations.AlterField(
            model_name='freshdeskticket',
            name='group_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the group to which the ticket has been assigned.', null=True),
        ),
        migrations.AlterField(
            model_name='freshdeskticket',
            name='requester_id',
            field=models.BigIntegerField(blank=True, help_text='User ID of the requester.', null=True),
        ),
        migrations.AlterField(
            model_name='freshdeskticket',
            name='responder_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the agent to whom the ticket has been assigned.', null=True),
        ),
    ]
