# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0030_auto_20160610_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshdeskconversation',
            name='from_email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='freshdeskconversation',
            name='freshdesk_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.FreshdeskTicket'),
        ),
    ]
