# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 04:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_auto_20160608_1400'),
        ('registers', '0031_auto_20160610_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshdeskContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Set to true if the contact has been verified.')),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('contact_id', models.BigIntegerField(help_text='ID of the contact.', unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('custom_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Key value pairs containing the names and values of custom fields.', null=True)),
                ('description', models.TextField(blank=True, help_text='A short description of the contact.', null=True)),
                ('email', models.CharField(blank=True, help_text='Primary email address of the contact.', max_length=256, null=True, unique=True)),
                ('job_title', models.CharField(blank=True, help_text='Job title of the contact.', max_length=256, null=True)),
                ('language', models.CharField(blank=True, help_text='Language of the contact.', max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, help_text='Mobile number of the contact.', max_length=256, null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the contact.', max_length=256, null=True)),
                ('other_emails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Additional emails associated with the contact. An array of strings.', null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the contact.', max_length=256, null=True)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Tags that have been associated with the contact. An array of strings.', null=True)),
                ('time_zone', models.CharField(blank=True, help_text='Time zone in which the contact resides.', max_length=256, null=True)),
                ('updated_at', models.DateTimeField(blank=True, help_text='Contact updated timestamp.', null=True)),
                ('du_user', models.ForeignKey(blank=True, help_text='Department User that is represented by this Freshdesk contact.', null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.DepartmentUser')),
            ],
        ),
        migrations.AddField(
            model_name='freshdeskconversation',
            name='freshdesk_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.FreshdeskContact'),
        ),
        migrations.AddField(
            model_name='freshdeskticket',
            name='freshdesk_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freshdesk_requester', to='registers.FreshdeskContact'),
        ),
        migrations.AddField(
            model_name='freshdeskticket',
            name='freshdesk_responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freshdesk_responder', to='registers.FreshdeskContact'),
        ),
    ]
