# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0032_auto_20160610_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itsystemhardware',
            options={'ordering': ('host__name',), 'verbose_name_plural': 'IT system hardware'},
        ),
    ]
