# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0033_auto_20160617_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsystem',
            name='availability_display',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='criticality_display',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='itsystem',
            name='system_type_display',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
    ]
