# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0034_auto_20160620_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessfunction',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='businessprocess',
            options={'ordering': ('name',), 'verbose_name_plural': 'business processes'},
        ),
        migrations.AlterModelOptions(
            name='businessservice',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='itsystem',
            options={'ordering': ('name',), 'verbose_name': 'IT System'},
        ),
        migrations.AlterModelOptions(
            name='itsystemdependency',
            options={'ordering': ('itsystem__name', 'criticality'), 'verbose_name': 'IT System dependency', 'verbose_name_plural': 'IT System dependencies'},
        ),
        migrations.AlterModelOptions(
            name='itsystemhardware',
            options={'ordering': ('host__name',), 'verbose_name_plural': 'IT System hardware'},
        ),
        migrations.AlterModelOptions(
            name='secondarylocation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ('name',), 'verbose_name_plural': 'software'},
        ),
        migrations.AlterModelOptions(
            name='softwarelicense',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='itsystem',
            name='request_access',
            field=models.TextField(blank=True, help_text='Procedure to request access to this application'),
        ),
    ]
