# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0035_auto_20160621_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='org_position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registers.OrgUnit'),
        ),
    ]
