# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0036_auto_20160725_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='sync_o365',
            field=models.BooleanField(default=True, help_text='Sync this to O365 (creates a security group).'),
        ),
    ]
