# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0038_auto_20160829_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='device',
            name='org_unit',
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='itsystem',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='softwarelicense',
            name='devices',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
