# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0039_auto_20160901_1039'),
    ]

    database_operations = [
        migrations.AlterModelTable('FreshdeskTicket', 'tracking_freshdeskticket'),
        migrations.AlterModelTable('FreshdeskConversation', 'tracking_freshdeskconversation'),
        migrations.AlterModelTable('FreshdeskContact', 'tracking_freshdeskcontact'),
    ]

    state_operations = [
        migrations.DeleteModel('FreshdeskTicket'),
        migrations.DeleteModel('FreshdeskConversation'),
        migrations.DeleteModel('FreshdeskContact'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations)
    ]
