# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0040_auto_20160901_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='license',
        ),
    ]
