# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 04:09
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0041_remove_software_license'),
    ]

    database_operations = [
        migrations.AlterModelTable('Vendor', 'assets_vendor'),
        migrations.AlterModelTable('SoftwareLicense', 'assets_softwarelicense'),
    ]

    state_operations = [
        migrations.DeleteModel('Vendor'),
        migrations.DeleteModel('SoftwareLicense'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
