# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0042_auto_20160902_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='location',
        ),
    ]
