# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 23:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sam_account_name', models.CharField(max_length=32, null=True, unique=True)),
                ('hostname', models.CharField(max_length=2048)),
                ('domain_bound', models.BooleanField(default=False)),
                ('ad_guid', models.CharField(max_length=48, null=True, unique=True)),
                ('ad_dn', models.CharField(max_length=512, null=True, unique=True)),
                ('pdq_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('sophos_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('asset_id', models.CharField(blank=True, help_text='OIM Asset ID', max_length=64, null=True)),
                ('finance_asset_id', models.CharField(blank=True, help_text='Finance asset ID', max_length=64, null=True)),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('chassis', models.CharField(max_length=128)),
                ('serial_number', models.CharField(max_length=128)),
                ('os_name', models.CharField(blank=True, max_length=128)),
                ('os_version', models.CharField(max_length=128)),
                ('os_service_pack', models.CharField(max_length=128)),
                ('os_arch', models.CharField(max_length=128)),
                ('cpu', models.CharField(max_length=128)),
                ('cpu_count', models.PositiveSmallIntegerField(default=0)),
                ('cpu_cores', models.PositiveSmallIntegerField(default=0)),
                ('memory', models.BigIntegerField(default=0)),
                ('date_pdq_updated', models.DateTimeField(blank=True, null=True)),
                ('date_nmap_updated', models.DateTimeField(blank=True, null=True)),
                ('date_sophos_updated', models.DateTimeField(blank=True, null=True)),
                ('date_ad_updated', models.DateTimeField(blank=True, null=True)),
                ('date_dhcp_updated', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ad_guid', models.CharField(editable=False, max_length=48, unique=True)),
                ('ad_dn', models.CharField(editable=False, max_length=512, unique=True)),
                ('ad_data', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
                ('org_data', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
                ('employee_id', models.CharField(max_length=128, null=True, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('username', models.CharField(editable=False, max_length=128, unique=True)),
                ('given_name', models.CharField(max_length=128, null=True)),
                ('surname', models.CharField(max_length=128, null=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(editable=False, max_length=254, unique=True)),
                ('expiry_date', models.DateTimeField(editable=False, null=True)),
                ('date_ad_updated', models.DateTimeField(editable=False, null=True)),
                ('telephone', models.CharField(blank=True, max_length=128, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('other_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('ad_deleted', models.BooleanField(default=False, editable=False)),
                ('in_sync', models.BooleanField(default=False, editable=False)),
                ('sso_roles', models.TextField(editable=False, help_text='Groups/roles separated by semicolon', null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tracking.DepartmentUser')),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ad_guid', models.CharField(max_length=48, null=True, unique=True)),
                ('ad_dn', models.CharField(max_length=512, null=True, unique=True)),
                ('asset_id', models.CharField(help_text='OIM Asset ID', max_length=64, null=True)),
                ('finance_asset_id', models.CharField(help_text='Finance asset ID', max_length=64, null=True)),
                ('model', models.CharField(max_length=128, null=True)),
                ('os_name', models.CharField(max_length=128, null=True)),
                ('identity', models.CharField(max_length=512, null=True, unique=True)),
                ('serial_number', models.CharField(max_length=128, null=True)),
                ('imei', models.CharField(max_length=64, null=True)),
                ('last_sync', models.DateTimeField(null=True)),
                ('registered_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.DepartmentUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='"Official" device owner/manager (set in AD).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computers_managed', to='tracking.DepartmentUser'),
        ),
        migrations.AddField(
            model_name='computer',
            name='probable_owner',
            field=models.ForeignKey(blank=True, help_text='Automatically-generated "most probable" device owner.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computers_probably_owned', to='tracking.DepartmentUser'),
        ),
    ]
