# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='last_ad_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='last_ad_login_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
