# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_auto_20151217_0705'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
        migrations.AddField(
            model_name='computer',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit'),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='org_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='cost_centre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit'),
        ),
    ]
