# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20151217_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='executive',
            field=models.BooleanField(default=False, help_text='An individual who is an executive'),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='vip',
            field=models.BooleanField(default=False, help_text='An individual who carries out a critical role for the department'),
        ),
    ]
