# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20170907_0940'),
        ('tracking', '0003_computer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='hardware_asset',
            field=models.ForeignKey(blank=True, help_text='OIM hardware asset register.', null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.HardwareAsset'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ad_dn',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True, verbose_name='AD distinguished name'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ad_guid',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True, verbose_name='AD GUID'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='chassis',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu_cores',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='memory',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_arch',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_service_pack',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_version',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='sam_account_name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='sAMAccountName'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
