# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 09:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0011_location_bandwidth_url'),
        ('tracking', '0005_auto_20160101_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Instance Name')),
                ('instance_id', models.CharField(max_length=200, unique=True, verbose_name='EC2 Instance ID')),
                ('start_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('scheduled_shutdown', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cost_centre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
