# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20170922_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='date_dhcp_updated',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='date_nmap_updated',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='date_sophos_updated',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='finance_asset_id',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='sophos_id',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='validation_notes',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='finance_asset_id',
        ),
        migrations.AddField(
            model_name='computer',
            name='ec2_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.EC2Instance', verbose_name='EC2 instance'),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='agent_version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SSM agent version'),
        ),
    ]
