# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_ec2instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ec2instance',
            old_name='instance_id',
            new_name='ec2id',
        ),
    ]
