# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 06:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20171017_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='AWS tags (key value pairs).', null=True),
        ),
    ]
