# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_ec2instance_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='pdq_id',
        ),
    ]
