# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20160119_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ec2instance',
            old_name='start_time',
            new_name='launch_time',
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='scheduled_shutdown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
