# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20160119_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ec2instance',
            name='scheduled_shutdown',
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='next_state',
            field=models.BooleanField(default=True, help_text='Checked is on, unchecked is off'),
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='running',
            field=models.BooleanField(default=True),
        ),
    ]
