# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_remove_computer_pdq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='hardware_asset',
        ),
    ]
