# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20160201_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='contractor',
            field=models.BooleanField(default=False, help_text='An individual who is an external contractor'),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to=tracking.models.get_photo_path),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='photo_ad',
            field=models.ImageField(blank=True, editable=False, upload_to=tracking.models.get_photo_ad_path),
        ),
    ]
