# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_auto_20160222_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ec2instance',
            options={'verbose_name': 'EC2 instance'},
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='notes',
            field=models.TextField(blank=True, help_text='Officer secondary roles, etc.', null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='working_hours',
            field=models.TextField(blank=True, default='9:00-17:00, Mon-Fri', help_text='Officer normal work/contact hours', null=True),
        ),
    ]
