# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0013_auto_20160303_1444'),
        ('tracking', '0011_auto_20160303_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='cost_centres_secondary',
            field=models.ManyToManyField(related_name='cost_centres_secondary', to='registers.CostCentre'),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='org_units_secondary',
            field=models.ManyToManyField(related_name='org_units_secondary', to='registers.OrgUnit'),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='populate_primary_group',
            field=models.BooleanField(default=True, help_text='If unchecked, user will not be added to primary group email'),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='secondary_locations',
            field=models.ManyToManyField(to='registers.Location'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='contractor',
            field=models.BooleanField(default=False, help_text='An individual who is an external contractor (does not include agency contract staff)'),
        ),
    ]
