# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20160310_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
        migrations.AlterField(
            model_name='ec2instance',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.CostCentre'),
        ),
    ]
