# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_auto_20160314_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='name_update_reference',
            field=models.CharField(blank=True, help_text='Reference for name/CC change request', max_length=512, null=True),
        ),
    ]
