# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_auto_20160517_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Dept fixed-term contract'), (1, 'N/A'), (2, 'Permanent'), (3, 'Recruitment agency contract'), (4, 'Resigned'), (5, 'Shared account'), (6, 'Vendor'), (7, 'Volunteer')], null=True),
        ),
    ]
