# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_auto_20160520_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Casual'), (0, 'Dept fixed-term contract'), (1, 'N/A'), (2, 'Permanent fulltime'), (8, 'Permanent part time'), (3, 'Recruitment agency contract'), (4, 'Resigned'), (5, 'Shared account'), (6, 'Vendor'), (7, 'Volunteer')], null=True),
        ),
    ]
