# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_auto_20160608_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='position_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Full time'), (1, 'Part time'), (2, 'Casual'), (3, 'Other')], default=0, help_text='Employee current position working arrangements.', null=True),
        ),
        migrations.AddField(
            model_name='departmentuser',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Employee-editable preferred name.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Casual'), (0, 'Dept fixed-term contract'), (1, 'N/A'), (2, 'Permanent fulltime'), (8, 'Permanent part time'), (3, 'Recruitment agency contract'), (4, 'Resigned'), (5, 'Shared account'), (6, 'Vendor'), (7, 'Volunteer')], help_text='Employee account status (should match Alesco status).', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text="HR Employee ID, use 'n/a' if a contractor", max_length=128, null=True, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Person that this employee reports to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tracking.DepartmentUser', verbose_name='Reports to'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='working_hours',
            field=models.TextField(blank=True, default='9:00-17:00, Mon-Fri', help_text='Employee normal work/contact hours', null=True),
        ),
    ]
