# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_auto_20160701_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Agency contract'), (0, 'Department fixed-term contract'), (1, 'Other'), (2, 'Permanent'), (4, 'Resigned'), (9, 'Role-based account'), (8, 'Seasonal'), (5, 'Shared account'), (6, 'Vendor'), (7, 'Volunteer')], help_text='Employee account status (should match Alesco status).', null=True),
        ),
    ]
