# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_auto_20160701_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentuser',
            name='security_clearance',
            field=models.BooleanField(default=False, help_text='Security clearance approved by CC Manager (confidentiality\n        agreement, referee check, police clearance, etc.', verbose_name='security clearance granted'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='account_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Agency contract'), (0, 'Department fixed-term contract'), (1, 'Other'), (2, 'Permanent'), (4, 'Resigned'), (9, 'Role-based account'), (8, 'Seasonal'), (5, 'Shared account'), (6, 'Vendor'), (7, 'Volunteer')], help_text='Employee account status (should match Alesco status)', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='given_name',
            field=models.CharField(help_text='Legal first name (matches birth certificate/password/etc.)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='name',
            field=models.CharField(help_text='Format: Surname, Given name', max_length=128),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registers.OrgUnit', verbose_name='organisational unit'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='position_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Full time'), (1, 'Part time'), (2, 'Casual'), (3, 'Other')], default=0, help_text='Employee position working arrangement (should match Alesco status)', null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='surname',
            field=models.CharField(help_text='Legal surname (matches birth certificate/password/etc.)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='title',
            field=models.CharField(help_text='Occupation position title (should match Alesco)', max_length=128, null=True),
        ),
    ]
