# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_auto_20160721_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='date_ad_updated',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Date AD updated'),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='working_hours',
            field=models.TextField(blank=True, default='N/A', help_text='Description of normal working hours', null=True),
        ),
    ]
