# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0023_auto_20160825_1504'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='departmentuser',
            managers=[
            ],
        ),
    ]
