# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 02:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0025_auto_20160901_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentuser',
            name='ad_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='departmentuser',
            name='org_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
    ]
