apiVersion: v1
kind: PersistentVolume
metadata:
  name: oim-cms-media-pv
  # Labels will be used by the claim to match the PV.
  # Define labels in the overlay patch.
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: oim-cms-azurefile
    secretNamespace: oim-cms
    # Define shareName in the overlay patch.
    # It needs to match the name of the file share exactly.
    readOnly: false
  mountOptions:
  - file_mode=0755
  - uid=33
  - gid=33
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oim-cms-media-pvc
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # To make sure we match the claim with the exact volume, match the `usage` label.
  # Define this selector in the overlay patch.
