# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('proposal_url', models.URLField(blank=True, help_text='Optional URL to the item that requires approval.', max_length=2000, null=True, verbose_name='proposal URL')),
                ('proposal_desc', models.TextField(blank=True, help_text='Optional description of the item that requires approval.', null=True, verbose_name='proposal description')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(help_text='The staff member that is requested to approve the item.', on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='organisation.DepartmentUser')),
                ('requester', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='organisation.DepartmentUser')),
            ],
        ),
    ]
